name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  ssh_test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/git/github-action-example
            git clean -fd
            git fetch
            git reset --hard origin/master
            ./run.sh
