name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  ssh_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get Commit Message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            cd ~/git/github-action-example
            git clean -fd
            git fetch
            git reset --hard origin/master
            cp .env.production .env -f
            echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" >/tmp/vault_password
            ansible-vault decrypt .env --vault-password-file=/tmp/vault_password
            rm /tmp/vault_password
            ./run.sh

      - name: Send Discord Notification on Success
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ **${GITHUB_REPOSITORY}** has been successfully deployed to \`${BRANCH_NAME}\` branch!\n**Commit Message:** ${COMMIT_MESSAGE}\n**Triggered By:** ${GITHUB_ACTOR}\n**Commit SHA:** ${COMMIT_SHA}\"}" \
          $DISCORD_WEBHOOK_URL

      - name: Send Discord Notification on Failure
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ **${GITHUB_REPOSITORY}** deployment to \`${BRANCH_NAME}\` branch failed.\n**Commit Message:** ${COMMIT_MESSAGE}\n**Triggered By:** ${GITHUB_ACTOR}\n**Commit SHA:** ${COMMIT_SHA}\nPlease check the logs for more details.\"}" \
          $DISCORD_WEBHOOK_URL
