name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  ssh_test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/git/github-action-example
            git clean -fd
            git fetch
            git reset --hard origin/master
            cp .env.production .env -f
            echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" >/tmp/vault_password
            ansible-vault decrypt .env --vault-password-file=/tmp/vault_password
            rm /tmp/vault_password
            ./run.sh

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Test SSH Connection job completed successfully!"}' \
          $DISCORD_WEBHOOK_URL
